# Generated by Django 5.1.5 on 2025-01-27 21:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='backend_skill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150)),
                ('iconlink', models.ImageField(upload_to='images/%Y/%m/%d')),
            ],
        ),
        migrations.CreateModel(
            name='file',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cvlink', models.FileField(upload_to='files/%Y/%m/%d')),
                ('filename', models.CharField(max_length=150, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='frontend_skill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150)),
                ('iconlink', models.ImageField(upload_to='images/%Y/%m/%d')),
            ],
        ),
        migrations.CreateModel(
            name='tool',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150)),
                ('iconlink', models.ImageField(upload_to='images/%Y/%m/%d')),
            ],
        ),
        migrations.DeleteModel(
            name='Backend',
        ),
        migrations.DeleteModel(
            name='Files',
        ),
        migrations.DeleteModel(
            name='Frontend',
        ),
        migrations.DeleteModel(
            name='Tools',
        ),
        migrations.AlterField(
            model_name='project',
            name='imagelink',
            field=models.ImageField(upload_to='images/%Y/%m/%d'),
        ),
    ]
