# Generated by Django 5.1.5 on 2025-01-27 22:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio_app', '0005_alter_backend_skill_iconlink_alter_file_cvlink_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='backend_skill',
            name='iconlink',
            field=models.FileField(upload_to='svg/%Y/%m/%d'),
        ),
        migrations.AlterField(
            model_name='frontend_skill',
            name='iconlink',
            field=models.FileField(upload_to='svg/%Y/%m/%d'),
        ),
        migrations.AlterField(
            model_name='tool',
            name='iconlink',
            field=models.FileField(upload_to='svg/%Y/%m/%d'),
        ),
    ]
