# Generated by Django 5.1.5 on 2025-01-27 21:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio_app', '0002_backend_skill_file_frontend_skill_tool_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='backend_skill',
            name='iconlink',
            field=models.ImageField(upload_to='media/images/%Y/%m/%d'),
        ),
        migrations.AlterField(
            model_name='file',
            name='cvlink',
            field=models.FileField(upload_to='media/files/%Y/%m/%d'),
        ),
        migrations.AlterField(
            model_name='frontend_skill',
            name='iconlink',
            field=models.ImageField(upload_to='media/images/%Y/%m/%d'),
        ),
        migrations.AlterField(
            model_name='tool',
            name='iconlink',
            field=models.ImageField(upload_to='media/images/%Y/%m/%d'),
        ),
    ]
