# Generated by Django 5.1.5 on 2025-01-27 21:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio_app', '0004_alter_project_imagelink'),
    ]

    operations = [
        migrations.AlterField(
            model_name='backend_skill',
            name='iconlink',
            field=models.ImageField(upload_to='images/%Y/%m/%d'),
        ),
        migrations.AlterField(
            model_name='file',
            name='cvlink',
            field=models.FileField(upload_to='files/%Y/%m/%d'),
        ),
        migrations.AlterField(
            model_name='frontend_skill',
            name='iconlink',
            field=models.ImageField(upload_to='images/%Y/%m/%d'),
        ),
        migrations.AlterField(
            model_name='project',
            name='imagelink',
            field=models.ImageField(upload_to='images/%Y/%m/%d'),
        ),
        migrations.AlterField(
            model_name='tool',
            name='iconlink',
            field=models.ImageField(upload_to='images/%Y/%m/%d'),
        ),
    ]
