# Generated by Django 5.1.5 on 2025-01-31 00:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio_app', '0006_alter_backend_skill_iconlink_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='sort_order',
            field=models.IntegerField(default=0),
        ),
    ]
